[package]
name = "renderbaby"
version = "0.1.0"
edition = "2024"

[dependencies]
mvc-view-wrappers = { path = "crates/mvc-view-wrappers" }
eframe = "0.33.0"
egui = "0.33.0"
env_logger = "0.11.8"
engine-wgpu-wrapper = { path = "crates/engine-wgpu-wrapper" }
scene = { path = "crates/scene" }
egui-file-dialog = "0.12.0"

[workspace]
members = [
    ".",
    "crates/engine-pathtracer",
    "crates/engine-raytracer",
    "crates/engine-wgpu-wrapper",
    "crates/engine-config",
    "crates/engine-main",
    "crates/scene-parser",
    "crates/scene",
    "crates/scene-obj-parser",
    "crates/mvc-view-wrappers",
]

