[package]
name = "renderbaby"
version = "0.1.0"
edition = "2024"

[dependencies]
control-plane = { path = "crates/control-plane" }

[workspace]
members = [
    ".", "crates/engine-config", "crates/engine-main",
    "crates/engine-pathtracer",
    "crates/engine-raytracer",
    "crates/engine-wgpu-wrapper",
    "crates/control-plane",
    "crates/engine-config",
    "crates/engine-main",
]
