[package]
name = "renderbaby"
version = "0.1.0"
edition = "2024"

[dependencies]
<<<<<<< HEAD
=======
computational-plane = { path = "crates/computational-plane" }
data-plane = { path = "crates/scene" }
>>>>>>> obj-parser-branch
control-plane = { path = "crates/control-plane" }
eframe = "0.33.0"
egui = "0.33.0"
engine-main = { path = "crates/engine-main" }
engine-raytracer = { path = "crates/engine-raytracer"}
engine-config = { path = "crates/engine-config" }
env_logger = "0.11.8"
log = "0.4.28"
anyhow = "1.0.100"
engine-wgpu-wrapper = { path = "crates/engine-wgpu-wrapper" }

[workspace]
members = [
<<<<<<< HEAD
    ".",
    "crates/engine-pathtracer",
    "crates/engine-raytracer",
    "crates/engine-wgpu-wrapper",
    "crates/control-plane",
    "crates/engine-config",
    "crates/engine-main",
=======
    "crates/computational-plane",
    "crates/scene",
    "crates/control-plane",
    ".",
>>>>>>> obj-parser-branch
]
