[package]
name = "engine-config"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
log = "0.4"
env_logger = "0.11"
engine-bvh = {path = "../engine-bvh"}
serde = { version = "1.0", features = ["derive"] }
frame-buffer = { path = "../frame-buffer" }