[package]
name = "data-plane"
version = "0.1.0"
edition = "2024"

[dependencies]
computational-plane = {path = "../computational-plane"}
log = "0.4"
env_logger = "0.11"
glam = { version = "0.30.9", default-features = false, features = ["libm"] }
