[package]
name = "scene-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { version = "0.30.9", default-features = false, features = ["libm"] }
scene = {path = "../scene"}
serde = { version = "1" , features = ["derive"] }
serde_json = "1"